export const MELBOURNE_SUBURBS: string[] = [
  "Abbotsford",
  "Albert Park",
  "Alphington",
  "Altona",
  "Altona Meadows",
  "Altona North",
  "Ardeer",
  "Armadale",
  "Ascot Vale",
  "Ashburton",
  "Ashwood",
  "Aspendale",
  "Aspendale Gardens",
  "Avondale Heights",
  "Balaclava",
  "Balwyn",
  "Balwyn North",
  "Bayswater",
  "Bayswater North",
  "Beaconsfield",
  "Beaumaris",
  "Belgrave",
  "Bentleigh",
  "Bentleigh East",
  "Black Rock",
  "Blackburn",
  "Blackburn North",
  "Blackburn South",
  "Boronia",
  "Box Hill",
  "Box Hill North",
  "Box Hill South",
  "Brighton",
  "Brighton East",
  "Broadmeadows",
  "Brooklyn",
  "Brunswick",
  "Brunswick East",
  "Brunswick West",
  "Bulleen",
  "Bundoora",
  "Burnley",
  "Burwood",
  "Burwood East",
  "Camberwell",
  "Canterbury",
  "Carlton",
  "Carlton North",
  "Carnegie",
  "Carrum",
  "Carrum Downs",
  "Caulfield",
  "Caulfield East",
  "Caulfield North",
  "Caulfield South",
  "Cheltenham",
  "Clarinda",
  "Clayton",
  "Clayton South",
  "Clifton Hill",
  "Coburg",
  "Coburg North",
  "Collingwood",
  "Coolaroo",
  "Craigieburn",
  "Cranbourne",
  "Croydon",
  "Croydon Hills",
  "Croydon North",
  "Croydon South",
  "Dallas",
  "Dandenong",
  "Dandenong North",
  "Diamond Creek",
  "Dingley Village",
  "Docklands",
  "Doncaster",
  "Doncaster East",
  "Donvale",
  "Doreen",
  "Eaglemont",
  "East Melbourne",
  "Edithvale",
  "Elsternwick",
  "Eltham",
  "Eltham North",
  "Elwood",
  "Endeavour Hills",
  "Epping",
  "Essendon",
  "Essendon North",
  "Essendon West",
  "Fairfield",
  "Fawkner",
  "Fitzroy",
  "Fitzroy North",
  "Flemington",
  "Footscray",
  "Forest Hill",
  "Glen Huntly",
  "Glen Iris",
  "Glen Waverley",
  "Glenroy",
  "Greensborough",
  "Greenvale",
  "Hallam",
  "Hampton",
  "Hampton East",
  "Hampton Park",
  "Hawthorn",
  "Hawthorn East",
  "Heidelberg",
  "Heidelberg Heights",
  "Heidelberg West",
  "Highett",
  "Hoppers Crossing",
  "Ivanhoe",
  "Ivanhoe East",
  "Keilor",
  "Keilor Downs",
  "Keilor East",
  "Keilor Lodge",
  "Keilor Park",
  "Kensington",
  "Kew",
  "Kew East",
  "Keysborough",
  "Kilsyth",
  "Kingsbury",
  "Kooyong",
  "Lalor",
  "Laverton",
  "Laverton North",
  "Lilydale",
  "Lower Plenty",
  "Macleod",
  "Malvern",
  "Malvern East",
  "Maribyrnong",
  "McKinnon",
  "Meadow Heights",
  "Melbourne",
  "Mentone",
  "Mernda",
  "Middle Park",
  "Mill Park",
  "Mitcham",
  "Moonee Ponds",
  "Moorabbin",
  "Mooroolbark",
  "Mordialloc",
  "Mount Waverley",
  "Murrumbeena",
  "Narre Warren",
  "Niddrie",
  "Noble Park",
  "North Melbourne",
  "Northcote",
  "Nunawading",
  "Oakleigh",
  "Oakleigh East",
  "Oakleigh South",
  "Officer",
  "Ormond",
  "Parkville",
  "Pascoe Vale",
  "Pascoe Vale South",
  "Point Cook",
  "Port Melbourne",
  "Prahran",
  "Preston",
  "Princes Hill",
  "Reservoir",
  "Richmond",
  "Ringwood",
  "Ringwood East",
  "Ringwood North",
  "Ripponlea",
  "Rosanna",
  "Roxburgh Park",
  "Saint Kilda",
  "Saint Kilda East",
  "Saint Kilda West",
  "Sandringham",
  "Seaford",
  "Seddon",
  "South Melbourne",
  "South Yarra",
  "Southbank",
  "Spotswood",
  "Springvale",
  "Springvale South",
  "St Albans",
  "Strathmore",
  "Sunbury",
  "Sunshine",
  "Sunshine North",
  "Sunshine West",
  "Surrey Hills",
  "Templestowe",
  "Templestowe Lower",
  "Thomastown",
  "Thornbury",
  "Toorak",
  "Tullamarine",
  "Vermont",
  "Vermont South",
  "Viewbank",
  "Wantirna",
  "Wantirna South",
  "Warrandyte",
  "Watsonia",
  "Watsonia North",
  "West Footscray",
  "Westmeadows",
  "Wheelers Hill",
  "Williamstown",
  "Williamstown North",
  "Windsor",
  "Wollert",
  "Yarraville",
];
